### ISSUE TITLE
FaceID does not work after restoring an iPhone 7+ backup on iPhone XS

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-mobile#119]
I had an archive with TouchID enabled in my iPhone Plus, and after migrating to iPhone XS and restoring the backup, I was unable to use "Touch Unlock" to log in to my old archive.

Removing the archive and adding a new archive and toggling Face ID fixed the issue.

Im thinking that there are 2 ways to fix this:

1- check if its possible to make it work with face id (they should be the same in theory because its just the OS saying "authenticated")
2- Showing a better alert (easiest)

![image](https://user-images.githubusercontent.com/768052/46245379-59745480-c3f5-11e8-8bef-462714c0f800.png)

**Comment by se1exin** [comment]
@sallar This should be mitigated in my upcoming PR for #125, as I've needed to make some changes to how Sources are stored to the device for AutoFill to work.

In summary, the issue you have described seems to be caused by your backup including the *flag* to say TouchID is enabled for the archive, but *not including* the corresponding Keychain entry for the archive. In #125 all storage is moved to the Keychain - it's not finalised whether these entries will be maintained during a backup/restore of iOS yet, but it should be possible to backup the Keychain as well.

Also putting this comment here to back link to #125 for future reference.

**Comment by perry-mitchell** [comment]
I guess this has been solved. Will close for now.
