### ISSUE TITLE
Error: Connection failed with NextCloud and .ovh extension

### ISSUE THREAD

**Issue by skriwell** [buttercup/buttercup-mobile#121]
Hello,
(My English is not good, so it's a translation of Google)
With the Android app, I can not connect to my NexCloud. I have the following message: "Error: Connection failed"
By cons with the desktop app, it works.
My Nexcloud uses the .ovh extension
The problem can come from there?

Thanks

**Comment by perry-mitchell** [comment]
Hi @skriwell - Unfortunately it's very difficult for us to debug these kind of issues without trying the connection ourselves. Do you use Keybase at all? It would be great if you could create me a limited account to test with, otherwise I'm not sure where we can go from here. This is me: https://keybase.io/perrymitchell

**Comment by perry-mitchell** [comment]
I'll close this due to inactivity. We can reopen if the issue is still present and we can get some more info on the matter.
