### ISSUE TITLE
Autofill extension crashes on iOS - v1.9

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#179]
The autofill extension crashes when opening it within the latest version. It arrived after the google drive integration was included. Repeated attempts to open it result in the same effect.

When in development the autofill app simply shows a white screen.

**Comment by se1exin** [comment]
@perry-mitchell Fix is ready in #181 (hopefully!)

**Comment by se1exin** [comment]
Weird, I'm unable to reproduce the issue on the `rn-59` branch. I *did* have to pretty much set the entire buttercup iOS dev environment up from scratch again due to all the stupid cache issues react-native has when anything changes in node_modules - so perhaps you are getting issues somewhere there?

Can you please retest the changes from #181 with a clean setup (RN cache clean, XCode clean, delete and reinstall pods, etc) and let me know how it goes?

<img width="455" alt="Screen Shot 2019-09-14 at 2 48 52 pm" src="https://user-images.githubusercontent.com/2385350/64903596-5f933c00-d6ff-11e9-9bad-ace363787032.png">

**Comment by perry-mitchell** [comment]
Will do! I’ll have a go at that this evening 👍

**Comment by perry-mitchell** [comment]
Seems to work locally with the latest updates, will try to publish this one today.

**Comment by perry-mitchell** [comment]
Released under 1.10.1 on iOS. Can re-open if the issue persists.

**Comment by perry-mitchell** [comment]
@se1exin Thanks a bunch for checking in on this!
