### ISSUE TITLE
Unable to edit some items in Buttercup iOS 12.4.6

### ISSUE THREAD

**Issue by houdini69** [buttercup/buttercup-mobile#243]
** Describe the issue you're having **

Tried to edit an item to no avail (I can't delete through the command because it's non responsive). This entry was imported from csv file previously through the desktop client. However, it's possible to delete a new entry.

** What OS version are you using **

iOS 12.4.6

** What device are you using **

iPhone 6

**Comment by perry-mitchell** [comment]
What connection are you using? How big is the vault? 

> I can't delete through the command because it's non responsive

What do you mean by this?

If you could attach a screen recording, that might help.

**Comment by houdini69** [comment]
I'm using webdav on Nextcloud and the vault is 623 ko.

I mean the Delete command doesn't respond.

I'am gonna try to attach a screen recording.

**Comment by houdini69** [comment]
I couldn't reproduce this issue. So I close it.

**Comment by ldexterldesign** [comment]
Hi all,

I think I may be able to help here...

If an entry is viewed via not a search result then edit feature is active
If an entry is viewed via a search result then edit feature is inactive

Rather than create a new issue let's reopen this one if someone else can reproduce

Hope this helps

Regards
